name: Deploy from Docker
on: 
    workflow_dispatch:
    push:
        branches: ['main']
jobs:
    Ci:
        runs-on: ubuntu-latest
        environment: Docker
        steps:
            - name: Use actions checkout
              uses: actions/checkout@v4

            - name: Login from Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./dockerfile
                push: true
                tags: |
                  falace/api_python:v1
                  falace/api_python:latest
            - name: Set config SSH Key
              run: |
                cat ${{ secrets.SSH_CONFIG }} > ~/.ssh/config
                cat ${{ secrets.SSH_KEY }} > ~/.ssh/github