name: Deploy from Docker
on: 
    workflow_dispatch:
    push:
        branches: ['main']

jobs:
    Build:
        runs-on: ubuntu-latest
        environment: Docker
        steps:
            - name: Use actions checkout
              uses: actions/checkout@v4

            - name: Login from Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./dockerfile
                push: true
                tags: |
                  falace/api_python:deploy-${{github.sha}}
                  falace/api_python:latest

    Deploy:
        runs-on: ubuntu-latest
        needs: Build
        environment: Docker
        steps:
            - name:  Create new repo
              run: mkdir ~/Pasta
              
            - name: Add ssh key
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Add git hub
              run: git clone ${{ secrets.REPO_GIT }} ~/Pasta
            

            - name: Create new manifest
              run: |
                cat > ~/Pasta/deployment-v1.yaml <<EOF
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: hello-api
                  namespace: argocd
                  labels:
                    app: hello-api
                spec:
                  strategy:
                    type: RollingUpdate
                    rollingUpdate:
                      maxUnavailable: 100%  
                      maxSurge: 0            
                  revisionHistoryLimit: 1
                  replicas: 3
                  selector:
                    matchLabels:
                      app: hello-api
                  template:
                    metadata:
                      labels:
                        app: hello-api
                    spec:
                      containers:
                        - name: hello-api
                          image: falace/api_python:deploy-${{github.sha}}
                          ports:
                            - containerPort: 8000
                          readinessProbe:
                            httpGet:
                              path: /
                              port: 8000
                            initialDelaySeconds: 5
                            periodSeconds: 10
                          livenessProbe:
                            httpGet:
                              path: /
                              port: 8000
                            initialDelaySeconds: 10
                            periodSeconds: 20

                ---

                apiVersion: v1
                kind: Service
                metadata:
                  name: hello-api
                  namespace: argocd
                spec:
                  type: NodePort
                  selector:
                    app: hello-api
                  ports:
                    - name: http
                      port: 8000
                      targetPort: 8000 
                      nodePort: 30080


                EOF
            
            - name: Pull Request
              run: |
                cd ~/Pasta
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                BRANCH="chore/new-manifest-${GITHUB_SHA::7}"
                git checkout -b "$BRANCH"
                git add .
                git commit -m "chore: add deployment-v2 with tag ${GITHUB_SHA::7}"
                git push -u origin "$BRANCH"
      