name: Deploy from Docker
on: 
    push:
        branches: ['main']
jobs:
    Ci:
        runs-on: ubuntu-latest
        steps:
            - name: Use actions checkout
              uses: actions/checkout@v4

            - name: Login from Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.Docker.DOCKER_USERNAME }}
                password: ${{ secrets.Docker.DOCKER_PASSWORD }}