name: Deploy from Docker
on: 
    workflow_dispatch:
    push:
        branches: ['main']

env:
  version: 
    'v1'

jobs:
    Build:
        runs-on: ubuntu-latest
        environment: Docker
        steps:
            - name: Use actions checkout
              uses: actions/checkout@v4

            - name: Login from Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./dockerfile
                push: true
                tags: |
                  falace/api_python:v1
                  falace/api_python:latest

    Deploy:
        runs-on: ubuntu-latest
        environment: Docker
        steps:
            - name:  Create new repo
              run: mkdir Pasta
            
            - name: Add git hub
              run: git clone https://github.com/alexsandroocanha/FastApi-Service-Manifests.git Pasta
            
            - name: Add ssh key
              run: |
                mkdir ~/.ssh/
                prinf "${{ secrets.SSH_KEY }}" >> ~/.ssh/github
                prinf "${{ secrets.SSH_CONFIG }}" >> ~/.ssh/config
                chmod 700 ~/.ssh/github
                chmod 700 ~/.ssh/config
                eval "$(ssh-agent -s)"
                ssh-add ~/.ssh/github